# Generated by Django 6.0 on 2025-12-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_education_resume_experience_resume_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='color',
            field=models.CharField(default='#2563eb', max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='template',
            field=models.CharField(default='modern', max_length=50),
        ),
    ]
