# Generated by Django 6.0 on 2025-12-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_color_resume_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('modern', 'Modern Resume')], default='modern', max_length=50),
        ),
    ]
