# Generated by Django 6.0 on 2025-12-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_alter_resume_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='work_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
