# Generated by Django 6.0 on 2025-12-19 10:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_resume_work_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='share_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
