# Generated by Django 6.0 on 2025-12-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_resume_share_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='share_id',
        ),
    ]
