# Generated by Django 6.0 on 2025-12-19 12:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_remove_resume_share_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
