# Generated by Django 6.0 on 2025-12-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_alter_resume_education_alter_resume_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('modern', 'Modern Resume'), ('professional', 'Professional Resume'), ('simple', 'Simple Resume'), ('creative', 'Creative Resume'), ('executive', 'Executive Resume'), ('minimalist', 'Minimalist Resume')], default='modern', max_length=50),
        ),
    ]
