# Generated by Django 6.0 on 2025-12-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0011_alter_resume_phone_resume_one_resume_per_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resume',
            name='one_resume_per_user',
        ),
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.CharField(default='modern', max_length=50),
        ),
    ]
